[program:edoc-queue-ocr]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/edoc/artisan queue:work database --queue=ocr --sleep=1 --tries=1 --timeout=720 --max-time=3600
directory=/var/www/edoc
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=750
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/edoc/storage/logs/queue-ocr.log

[program:edoc-queue-default]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/edoc/artisan queue:work database --queue=documents,notifications,default --sleep=1 --tries=3 --timeout=120 --max-time=3600
directory=/var/www/edoc
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=150
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/edoc/storage/logs/queue-default.log

[program:edoc-scheduler]
command=/usr/bin/php /var/www/edoc/artisan schedule:work
directory=/var/www/edoc
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/edoc/storage/logs/scheduler.log
